name: PR Automation Workflow

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - fix/*

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check package.json
        uses: tj-actions/changed-files@v42.0.4
        id: package-json
        with:
          files: |
            package.json

      - name: Check CHANGELOG.md
        uses: tj-actions/changed-files@v42.0.4
        id: changelog
        with:
          files: |
            CHANGELOG.md

      - name: Check LICENSE
        uses: tj-actions/changed-files@v42.0.4
        id: license
        with:
          files: |
            LICENSE

      - name: Verify Changes
        run: |
          if [[ "${{ steps.package-json.outputs.any_changed }}" == 'false' ]] || [[ "${{ steps.changelog.outputs.any_changed }}" == 'false' ]] || [[ "${{ steps.license.outputs.any_changed }}" == 'false' ]]; then
            echo "Error: package.json, CHANGELOG.md, and LICENSE must all be updated."
            exit 1
          fi

  auto-create-pr-to-dev-main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Auto-create PR to dev for release branches
        uses: peter-evans/create-pull-request@v3
        with:
          branch: sync-${{ github.head_ref }}-to-dev
          base: dev
          title: "[AUTO] Sync ${{ github.head_ref }} to dev"
          body: "Automated PR to sync changes from ${{ github.head_ref }} to dev."
          token: ${{ secrets.GITHUB_TOKEN }}

  mirror-fix-to-dev:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && contains(github.head_ref, 'fix/')
    steps:
      - uses: actions/checkout@v2
      - name: Auto-create PR to dev for fix branches
        uses: peter-evans/create-pull-request@v3
        with:
          branch: sync-${{ github.head_ref }}-to-dev
          base: dev
          title: "[AUTO] Sync ${{ github.head_ref }} to dev"
          body: "Automated PR to sync changes from ${{ github.head_ref }} to dev."
          token: ${{ secrets.GITHUB_TOKEN }}
