name: PR Automation Workflow

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - fix/*

jobs:
  check-updates:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'fix/') || contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Check for versioning changes in package.json and CHANGELOG.md
        run: |
          git fetch --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          PACKAGE_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} -- 'package.json')
          CHANGELOG_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} -- 'CHANGELOG.md')
          if [[ -z "$PACKAGE_CHANGED" || -z "$CHANGELOG_CHANGED" ]]; then
              echo "::error::package.json and CHANGELOG.md must be updated."
              exit 1
          fi

  auto-create-pr-to-dev-main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Auto-create PR to dev for release branches
        uses: peter-evans/create-pull-request@v3
        with:
          branch: sync-${{ github.head_ref }}-to-dev
          base: dev
          title: "[AUTO] Sync ${{ github.head_ref }} to dev"
          body: "Automated PR to sync changes from ${{ github.head_ref }} to dev."
          token: ${{ secrets.GITHUB_TOKEN }}

  mirror-fix-to-dev:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && contains(github.head_ref, 'fix/')
    steps:
      - uses: actions/checkout@v2
      - name: Auto-create PR to dev for fix branches
        uses: peter-evans/create-pull-request@v3
        with:
          branch: sync-${{ github.head_ref }}-to-dev
          base: dev
          title: "[AUTO] Sync ${{ github.head_ref }} to dev"
          body: "Automated PR to sync changes from ${{ github.head_ref }} to dev."
          token: ${{ secrets.GITHUB_TOKEN }}
