name: PR Automation Workflow

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - fix/*

jobs:
  check-updates:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'fix/') || contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Check for versioning changes in package.json and CHANGELOG.md
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          PACKAGE_CHANGED=$(git diff --name-only ${{ github.base_ref }}...HEAD -- package.json)
          CHANGELOG_CHANGED=$(git diff --name-only ${{ github.base_ref }}...HEAD -- CHANGELOG.md)
          if [ -z "$PACKAGE_CHANGED" ] || [ -z "$CHANGELOG_CHANGED" ]; then
          echo "::error::package.json and CHANGELOG.md must be updated."
          exit 1
          fi

  auto-create-pr-to-dev-main:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Auto-create PR to dev when PR to main
        if: github.base_ref == 'main'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "sync-dev-${{ github.event.pull_request.head.ref }}"
          base: dev
          title: "Sync ${{ github.event.pull_request.head.ref }} into dev"
          body: "This is an automated PR to keep dev in sync with the release."
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-create PR to main when PR to dev
        if: github.base_ref == 'dev'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "sync-main-${{ github.event.pull_request.head.ref }}"
          base: main
          title: "Sync ${{ github.event.pull_request.head.ref }} into main"
          body: "This is an automated PR to keep main in sync with the release."
          token: ${{ secrets.GITHUB_TOKEN }}

  mirror-fix-to-dev:
    runs-on: ubuntu-latest
    needs: check-updates
    if: github.base_ref == 'main' && contains(github.head_ref, 'fix/')
    steps:
      - uses: actions/checkout@v2
      - name: Auto-create PR to dev for fix branches
        uses: peter-evans/create-pull-request@v3
        with:
          branch: fix/${{ github.event.pull_request.head.ref }}
          base: dev
          title: "Merge ${{ github.event.pull_request.head.ref }} into dev"
          body: |
            This is an automated PR to keep dev up to date with fix ${GITHUB_REF##*/}.
          token: ${{ secrets.GITHUB_TOKEN }}
