name: CI Workflow

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1.1.1
        with:
          version: nightly

      - name: Lint, Build, and Test
        run: |
          yarn lint:sol
          yarn build
          yarn test

      - name: Install lcov for coverage reporting
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Upload Foundry Coverage Report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./coverage/foundry/lcov.info
          flags: foundry
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Hardhat Coverage Report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./coverage/lcov.info
          flags: hardhat
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Slither Analysis
        run: slither . --filter-paths "contracts/mock|node_modules" --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/contracts/

      - name: Post Slither Analysis as PR Comment
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const header = '# Slither report';
            const body = process.env.REPORT;
            const script = require('.github/scripts/comment');
            await script({ github, context, header, body });
        env:
          REPORT: ${{ steps.slither_analysis.outputs.stdout }}
