name: Unified CI Workflow

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-cache-key: ${{ steps.cache-keys.outputs.cache-key }}
      foundry-cache-key: ${{ steps.cache-foundry.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4.1.1

      # Generate cache key for node_modules based on the hash of yarn.lock
      - name: Get node cache key
        id: cache-keys
        run: echo "::set-output name=cache-key::$(echo ${{ runner.os }}-node-$(cat yarn.lock | sha256sum | cut -d' ' -f1))"

      # Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ steps.cache-keys.outputs.cache-key }}

      # Setup Node.js and Yarn cache
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'
          cache: 'yarn'

      # Install JavaScript Dependencies
      - name: Install JavaScript Dependencies
        run: yarn install --frozen-lockfile

      # Generate a unique cache key for Foundry based on the Foundry version
      - name: Get Foundry cache key
        id: cache-foundry-key
        run: echo "::set-output name=cache-key::$(echo ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml', '**/.foundry/**') }})"

      # Cache Foundry Toolchain
      - name: Cache Foundry Toolchain
        id: cache-foundry
        uses: actions/cache@v2
        with:
          path: |
            ~/.foundry
          key: ${{ steps.cache-foundry-key.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      # Conditionally install Foundry only if it wasn't restored from cache
      - name: Install Foundry and dependencies
        uses: foundry-rs/foundry-toolchain@v1.1.1
        with:
          version: nightly
        if: steps.cache-foundry.outputs.cache-hit != 'true'

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint sources
        run: yarn lint:sol

  unit_test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run Forge and Hardhat Tests
        run: |
          echo "primary twist rack vendor diagram image used route theme frown either will" > .secret
          yarn build
          yarn test

  coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Generate Hardhat & Foundry Coverage Report
        run: yarn coverage:report
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage/foundry/lcov.info,./coverage/lcov.info
          flags: foundry,hardhat
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  slither_analysis:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        with:
          slither-version: "0.10.0"
          fail-on: "none"
          slither-args: '--filter-paths "contracts/mock|node_modules" --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/contracts/'
      - name: Create/update checklist as PR comment
        uses: actions/github-script@v7.0.1
        env:
          REPORT: ${{ steps.slither_analysis.outputs.stdout }}
        with:
          script: |
            const script = require('.github/scripts/comment')
            const header = '# Slither report'
            const body: ${{ steps.slither_analysis.outputs.stdout }}
            await script({ github, context, header, body })
